/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/email` | `/email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/settings/availability`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/loyalty`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/promotions`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/new`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/clients/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/promotions/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/email` | `/email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/availability`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/loyalty`; params?: Router.UnknownOutputParams; } | { pathname: `/services`; params?: Router.UnknownOutputParams; } | { pathname: `/promotions`; params?: Router.UnknownOutputParams; } | { pathname: `/team`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/new`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/clients/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/services/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/promotions/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/email${`?${string}` | `#${string}` | ''}` | `/email${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clients${`?${string}` | `#${string}` | ''}` | `/clients${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/settings/availability${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settings/loyalty${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `/promotions${`?${string}` | `#${string}` | ''}` | `/team${`?${string}` | `#${string}` | ''}` | `/appointments/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/settings/availability`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/loyalty`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/promotions`; params?: Router.UnknownInputParams; } | { pathname: `/team`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/new`; params?: Router.UnknownInputParams; } | `/appointments/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/clients/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/services/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/promotions/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/appointments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/clients/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/promotions/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
